### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by birdayz** [birdayz/kaf#83]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x8795b8]

goroutine 69 [running]:
sync.(*Mutex).Lock(...)
        /usr/lib/go/src/sync/mutex.go:74
github.com/Shopify/sarama.(*Broker).send(0x0, 0xe1fac0, 0xc00034b1a0, 0xc000486001, 0x0, 0x0, 0x0)
        /home/j0e/gopath/pkg/mod/github.com/!shopify/sarama@v1.23.0/broker.go:663 +0x58
github.com/Shopify/sarama.(*Broker).sendAndReceive(0x0, 0xe1fac0, 0xc00034b1a0, 0xe0f0a0, 0xc000486000, 0x0, 0x0)
        /home/j0e/gopath/pkg/mod/github.com/!shopify/sarama@v1.23.0/broker.go:709 +0x72
github.com/Shopify/sarama.(*Broker).GetAvailableOffsets(0x0, 0xc00034b1a0, 0x0, 0x0, 0x0)
        /home/j0e/gopath/pkg/mod/github.com/!shopify/sarama@v1.23.0/broker.go:327 +0x70
main.getHighWatermarks.func1(0x7ffe76fd06a3, 0x13, 0xc00046f260, 0xc0003dd300, 0x0, 0xc00034b1a0)
        /home/j0e/projects/kaf/cmd/kaf/group.go:410 +0x4d
created by main.getHighWatermarks
        /home/j0e/projects/kaf/cmd/kaf/group.go:409 +0x4b6
```

**Comment by rpn0709** [comment]
i get the same when trying to describe a group.

**Comment by birdayz** [comment]
can you post your stacktrace please?
