### ISSUE TITLE
panic when creating topics

### ISSUE THREAD

**Issue by CrystalMethod** [birdayz/kaf#93]
I'm sure I've done this before.
```
kaf topic create test

panic: unable to redefine 'c' shorthand in "create" flagset: it's already used for "compact" flag

goroutine 1 [running]:
github.com/birdayz/kaf/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000106b00, 0xc00013b180)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/pflag/flag.go:862 +0x6d7
github.com/birdayz/kaf/vendor/github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc00013b180)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/pflag/flag.go:875 +0xa8
github.com/birdayz/kaf/vendor/github.com/spf13/pflag.(*FlagSet).VisitAll(0xc000107200, 0xc0001e3b68)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/pflag/flag.go:278 +0x94
github.com/birdayz/kaf/vendor/github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc000106b00, 0xc000107200)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/pflag/flag.go:873 +0x58
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).mergePersistentFlags(0x4f2fda0)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:1572 +0x90
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.stripFlags(0xc0001a2e20, 0x1, 0x1, 0x4f2fda0, 0x1, 0x0, 0x1)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:538 +0x51
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).Find.func1(0x4f2fda0, 0xc0001a2e20, 0x1, 0x1, 0x6, 0xc0001a2e20, 0x1, 0x1)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:597 +0x5c
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).Find.func1(0x4f2f3a0, 0xc00000fb80, 0x2, 0x2, 0x5, 0xc00000fb80, 0x2, 0x2)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:605 +0x119
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).Find.func1(0x4f2daa0, 0xc0000200d0, 0x3, 0x3, 0x1, 0x1, 0x3, 0x48b5450)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:605 +0x119
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).Find(0x4f2daa0, 0xc0000200d0, 0x3, 0x3, 0x5, 0xc00013b7c0, 0x489f3d7, 0xc0001e3ec0, 0x4394217, 0xc000106c00)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:610 +0x8c
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4f2daa0, 0x48a474d, 0xc0001e3f50, 0x4007b1f)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:895 +0x60c
github.com/birdayz/kaf/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/lars/projects/go/src/github.com/birdayz/kaf/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /Users/lars/projects/go/src/github.com/birdayz/kaf/cmd/kaf/kaf.go:105 +0x31
```

**Comment by CrystalMethod** [comment]
#84

**Comment by CrystalMethod** [comment]
I was still using an older release.
